email_cfg:
  server: 123
  username: 123
  password: 123
db_cfg:
  driver: postgres
  host: postgres
  port: 5432
  username: wangbo
  password: Wb@qwer4321
  database: wangbo
  ssl_mode: disable
  max_open: 5
  max_idle: 5
  conn_max_life: 30s
log_cfg:
  level: info
  dir: /app/logs

redis_cfg:
  addrs:
    - redis:6379
  password:
  db: 0
ca:
  provider: "aliyun"
  aliyun:
    endpoint: "https://ca.aliyuncs.com"
    access_key_id: "123"
    access_key_secret: "123"
    parent_identifier: "123"

user_jwt_secret: dadadadadaxxdad
iot:
  broker_url: "YOUR_MQTT_BROKER_URL" # 例如: "tcp://localhost:1883" 或 "ssl://mqtt.example.com:8883"
  client_id: "YOUR_MQTT_CLIENT_ID"
  username: "YOUR_MQTT_USERNAME"
  password: "YOUR_MQTT_PASSWORD"
  keep_alive_seconds: 60
  connect_timeout_seconds: 30
  max_reconnect_seconds: 30
  clean_session: false
