version: "3.7"

services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: openindustrial-mqtt-broker
    ports:
      - "1883:1883" # MQTT
      - "9001:9001" # WebSocket
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

volumes:
  mosquitto_data:
  mosquitto_log:
