package executors

import (
	"context"
	"errors"
	"fmt"
	"strings"
)

// SNWriteExecutor records a serial number provided by an external system.
//
// The MES does not generate the serial number here.
// The serial number is normally generated by an upstream factory system,
// programming station, or other production software and then written
// into the execution operation as production data.
type SNWriteExecutor struct {
}

func NewSNWriteExecutor() *SNWriteExecutor {
	return &SNWriteExecutor{}
}

func (e *SNWriteExecutor) Type() string {
	return OperationTypeSNWrite
}

func (e *SNWriteExecutor) Validate(
	ctx context.Context,
	input *OperationInput,
) error {
	if input == nil {
		return errors.New("operation input is nil")
	}

	if input.ExecutionID == 0 {
		return errors.New("execution ID is required")
	}

	if input.ExecutionOperationID == 0 {
		return errors.New("execution operation ID is required")
	}

	if input.ProductID == 0 {
		return errors.New("product ID is required")
	}

	if input.Parameters == nil {
		return errors.New("operation parameters are required")
	}

	serialNumber, ok := input.Parameters["serial_number"].(string)
	if !ok {
		return errors.New("serial_number must be a string")
	}

	if strings.TrimSpace(serialNumber) == "" {
		return errors.New("serial_number is required")
	}

	return nil
}

func (e *SNWriteExecutor) Execute(
	ctx context.Context,
	input *OperationInput,
) (*OperationOutput, error) {
	if err := e.Validate(ctx, input); err != nil {
		return nil, err
	}

	serialNumber := strings.TrimSpace(
		input.Parameters["serial_number"].(string),
	)

	if serialNumber == "" {
		return nil, fmt.Errorf("serial_number is empty")
	}

	return &OperationOutput{
		Result: map[string]any{
			// Keep serial_number at the top level because the
			// manufacturing result -> device identity extraction
			// reads the canonical device identity from here.
			"serial_number": serialNumber,

			// Keep the existing item structure for production
			// operation consumers that need the detailed result.
			"items": []map[string]any{
				{
					"item_key": input.Parameters["item_key"],
					"data": map[string]any{
						"serial_number": serialNumber,
					},
				},
			},
		},
	}, nil
}
