package gateway

import (
	"time"

	"github.com/google/uuid"
)

// Gateway represents an edge gateway device registered in the cloud.
type Gateway struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	OrgID       uuid.UUID `json:"org_id"`
	Status      string    `json:"status"` // e.g., "Online", "Offline", "Unregistered"
	LastSeenAt  time.Time `json:"last_seen_at"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// NewGateway creates a new Gateway entity.
func NewGateway(orgID uuid.UUID, name string) (*Gateway, error) {
	if name == "" {
		return nil, ErrGatewayNameRequired
	}

	now := time.Now().UTC()
	return &Gateway{
		ID:         uuid.New(), // The ID can be generated by the gateway itself upon first registration
		Name:       name,
		OrgID:      orgID,
		Status:     "Offline",
		LastSeenAt: now,
		CreatedAt:  now,
		UpdatedAt:  now,
	}, nil
}